spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springjooq?autoReconnect=true&serverTimezone=UTC
    username: springjooquser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080